### PR TITLE
Update rjsf and remove omit blur

### LINKED ISSUE #179: Upgrade rjsf to >=5.18.6 and remove performance workaround
**Is your feature request related to a problem? Please describe.**
Previously we added a custom `omitExtraDataOnBlur` event handler as workaround for an RJSF `omitExtraData` bug (in PR #171). I contributed a fix to rjsf and it was released in v5.18.6.

**Describe the solution you'd like**
- Update RJSF version to >= 5.18.6
- Remove `omitExtraDataOnBlur` workaround
- Check performance issues are further improved
- Check update rjsf version does not break anything

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by micahwoodard**
fixes #179 #160 
- update rjsf in package and package_lock json
- remove omitExtraDataOnBlur  function
-  swapped order of optional decimal to fix camera assemblies and stick microscopes

### CODE REVIEW

**Comment by micahwoodard** [comment]
**Empty Rig:** 
  -  Upgraded rjsf keystroke:  50-60ms
  -  omitExtraDataOnBlur:  70-100ms

**Fillled Rig:**
  -  Upgraded rjsf keystroke:  ~200ms
  - omitExtraDataOnBlur:  350-500ms
 
I also noticed some buggy behavior on the camera assemblies and stick microscopes where they flash open and then collapse. I've included a video.  I checked on dev, and the behavior persist so not sure if this is a bug or if maybe I'm missing data or something. 


https://github.com/user-attachments/assets/ca22493d-a0fe-45e3-bd82-32d1330c2ae5

**Comment by helen-m-lin** [comment]
> I also noticed some buggy behavior on the camera assemblies and stick microscopes where they flash open and then collapse. 

Thanks for flagging that, Micah! I'll take a look. We had that issue previously in #160. The `CustomTextWidget` may need to be updated.

**Comment by helen-m-lin** [comment]
@micahwoodard I think the issue has to do with the decimal handler in `schemaHandlers.js`. Looks like if you swap the order of the optional decimal, things work.
```
prop.anyOf = [{ title: 'decimal', type: 'string', pattern: '^-?\\d+(\\.\\d{1,})?$' }, { type: 'null', title: 'null' }]
```

**Comment by micahwoodard** [comment]
Yay thanks for investigating that! Push a fix

**Review by helen-m-lin — CHANGES_REQUESTED** [review]
Thanks Micah! Looks good. I pushed some tests that needed to be updated. Could you check the tests all succeed now? and that npm install works.

**Review by helen-m-lin — APPROVED** [review]

**Pull request merged**
