### PR TITLE
update schemas from aind-data-schema

### LINKED ISSUE #40: update metadata entry app schemas to use `aind-data-schema`  repo
For now just continue to hardcode this.  

`Subject.schema_json(indent=3)`

### PR DESCRIPTION
**Pull request by mekhlakapoor**
Closes #40

### CODE REVIEW

**Review by dyf — COMMENTED** [review]
@mekhlakapoor do we need to figure out how to render out the `$schema` tag?

**Comment by mekhlakapoor** [comment]
aind-data-schema repo doesn't have ophys schemas yet. also, there are extra fields due to docstrings in the data-schema scripts (ex: "procedure" field in Headframe with description "generic device type") and "TODO" in description fields
Screen Shot 2022-11-01 at 2 45 21 PM

**Comment by mekhlakapoor** [comment]
> @mekhlakapoor do we need to figure out how to render out the `$schema` tag?

I think it'd be good to have it in the schemas, but it doesn't need to be rendered (we didn't have it rendered before either).

**Comment by mekhlakapoor** [comment]
waiting on aind-data-schema coords to be resolved to update ephys session schema

**Review by jtyoung84 — APPROVED** [review]

**Pull request merged**
